kind: pipeline
name: lint & validate plugins
type: docker

steps:
  - name: lint & validate
    image: node:18-alpine
    commands:
      - npm ci
      - npm run lint
      - npm run validate
  - name: generate Plugins JSON
    image: node:18-alpine
    commands:
      - npm run gen-plugins-json
