workspace:
  path: src

pipeline:
  generate:
    image: golang:1.11
    commands:
      - go run scripts/gen-language-content.go

  build:
    image: plugins/hugo:latest
    validate: true

  publish:
    image: plugins/s3-sync:1.1
    access: public-read
    region: us-east-1
    bucket: plugins.drone.io
    source: public/
    target: /
    delete: false
    content_type:
      ".svg": image/svg+xml
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event: push
      branch: master
